
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

client1:
    container_name: client1
    image: client:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - CLIENT_ID=client1
    - SERVER_IP=server
    networks:
    - testing_net

client2:
    container_name: client2
    image: client:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - CLIENT_ID=client2
    - SERVER_IP=server
    networks:
    - testing_net

client3:
    container_name: client3
    image: client:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - CLIENT_ID=client3
    - SERVER_IP=server
    networks:
    - testing_net

client4:
    container_name: client4
    image: client:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - CLIENT_ID=client4
    - SERVER_IP=server
    networks:
    - testing_net

client5:
    container_name: client5
    image: client:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - CLIENT_ID=client5
    - SERVER_IP=server
    networks:
    - testing_net

client6:
    container_name: client6
    image: client:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - CLIENT_ID=client6
    - SERVER_IP=server
    networks:
    - testing_net

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24

